version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/template"
    update_schedule: "live"
    default_labels:
      - "dependabot"
    allowed_updates:
      - match:
          dependency_type: "direct"
          update_type: "all"
      - match:
          dependency_type: "indirect"
          update_type: "security"

    automerged_updates:
      - match:
          dependency_type: "development"
          dependency_name: "@sanity/*"
